name: regression tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04

    # Env vars for the application (same as on the .env files)
    env:

      NEXT_PUBLIC_MAPBOX_API_ACCESS_TOKEN: ${{ secrets.NEXT_PUBLIC_MAPBOX_API_ACCESS_TOKEN }}
      AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
      AUTH0_ISSUER_BASE_URL: ${{ secrets.AUTH0_ISSUER_BASE_URL }}
      AUTH0_BASE_URL: ${{ secrets.AUTH0_BASE_URL }}
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
      AUTH0_ACTIONS_HOOK_SECRET: ${{ secrets.AUTH0_ACTIONS_HOOK_SECRET }}

      AUTH0_MTM_BACKEND_DOMAIN: ${{ secrets.AUTH0_MTM_BACKEND_DOMAIN }}
      AUTH0_MTM_BACKEND_CLIENT_ID: ${{ secrets.AUTH0_MTM_BACKEND_CLIENT_ID }}
      AUTH0_MTM_BACKEND_CLIENT_SECRET: ${{ secrets.AUTH0_MTM_BACKEND_CLIENT_SECRET }}

      DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      # AUTH0_SESSION_COOKIE_NAME: ${{ secrets.AUTH0_SESSION_COOKIE_NAME }}
      # AUTH0_USERNAME: ${{ secrets.AUTH0_USERNAME }}
      # AUTH0_PASSWORD: ${{ secrets.AUTH0_PASSWORD }}
      # AUTH0_NEW_USER_USERNAME: ${{ secrets.AUTH0_NEW_USER_USERNAME }}
      # AUTH0_NEW_USER_PASSWORD: ${{ secrets.AUTH0_NEW_USER_PASSWORD }}
      # AUTH0_SCOPE: ${{ secrets.AUTH0_SCOPE }}
      # AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}

      IS_CI: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
        # Env vars for Cypress
        env:
          CYPRESS_auth0Audience: ${{ secrets.AUTH0_AUDIENCE }}
          CYPRESS_auth0Domain: ${{ secrets.AUTH0_DOMAIN }}
          CYPRESS_auth0ClientId: ${{ secrets.AUTH0_CLIENT_ID }}
          CYPRESS_auth0ClientSecret: ${{ secrets.AUTH0_CLIENT_SECRET }}
          CYPRESS_auth0CookieSecret: ${{ secrets.AUTH0_SECRET }}
          CYPRESS_auth0Scope: ${{ secrets.AUTH0_SCOPE }}
          CYPRESS_auth0SessionCookieName: ${{ secrets.AUTH0_SESSION_COOKIE_NAME }}
          CYPRESS_auth0LogoutUrl: /api/auth/logout
          CYPRESS_auth0ReturnToUrl: /
          CYPRESS_auth0Username: ${{ secrets.AUTH0_USERNAME }}
          CYPRESS_auth0Password: ${{ secrets.AUTH0_PASSWORD }}
          CYPRESS_auth0NewUserUsername: ${{ secrets.AUTH0_NEW_USER_USERNAME }}
          CYPRESS_auth0NewUserPassword: ${{ secrets.AUTH0_NEW_USER_PASSWORD }}
