name: regression tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04

    env:
      # Env vars are defined via GitHub for testing against the preview environment
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AUTH0_SESSION_COOKIE_NAME: ${{ secrets.AUTH0_SESSION_COOKIE_NAME }}
      AUTH0_USERNAME: ${{ secrets.AUTH0_USERNAME }}
      AUTH0_PASSWORD: ${{ secrets.AUTH0_PASSWORD }}
      AUTH0_NEW_USER_USERNAME: ${{ secrets.AUTH0_NEW_USER_USERNAME }}
      AUTH0_NEW_USER_PASSWORD: ${{ secrets.AUTH0_NEW_USER_PASSWORD }}

      AUTH0_ISSUER_BASE_URL: ${{ secrets.AUTH0_ISSUER_BASE_URL }}
      AUTH0_BASE_URL: ${{ secrets.AUTH0_BASE_URL }}

      AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
      AUTH0_SCOPE: ${{ secrets.AUTH0_SCOPE }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
      AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
